import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Navbar from "../components/Navbar.jsx";
import Footer from "../components/Footer.jsx";
import JourneySection from "../components/JourneySection.jsx";
import { BlurIn, Marquee, Reveal, SpotlightCard, Stagger, staggerItem } from "../ui/MotionPrimitives.jsx";
import { CANOPY_GENERATOR_IMAGE, GENERATOR_IMAGE, HERO_IMAGE, PARTS_STOCK_IMAGE, PANEL_IMAGE } from "../ui/media.js";
import { getServices } from "../api/services.js";
import { getGenerators } from "../api/generators.js";
import { motion } from "motion/react";
import "../ui/site.css";

const fallbackServices = ["Generator sales", "Generator purchase", "Generator rental", "Generator repair", "Generator maintenance", "ATS panels"];
const fallbackGenerators = [{ name: "100 kVA diesel generator systems", kva: "100+", image_url: HERO_IMAGE }];
const proofPoints = [{ no: "01", title: "A practical brief", text: "We begin with load, site and operating reality — not a generic product pitch.", href: "/contact", link: "Start with your brief" }, { no: "02", title: "One connected system", text: "Generation, ATS/AMF automation and technical support are planned together.", href: "/services", link: "Explore our services" }, { no: "03", title: "Support after handover", text: "Maintenance, parts and response keep the investment useful long after delivery.", href: "/services/generator-maintenance", link: "See maintenance support" }];

export default function Home() {
  const [services, setServices] = useState(fallbackServices.map((name) => ({ name, slug: name.toLowerCase().replaceAll(" ", "-") })));
  const [generators, setGenerators] = useState(fallbackGenerators);
  useEffect(() => { Promise.allSettled([getServices(), getGenerators()]).then(([s, g]) => { if (s.status === "fulfilled" && s.value?.length) setServices(s.value); if (g.status === "fulfilled" && g.value?.length) setGenerators(g.value); }); }, []);
  return <div className="site-page"><Navbar /><main>
    <section className="home-hero"><div className="home-hero-media"><img src={HERO_IMAGE} alt="100 kVA diesel generator" /></div><div className="home-hero-overlay" /><div className="site-shell home-hero-content"><Reveal><span className="eyebrow">Power generation / Islamabad</span></Reveal><BlurIn delay={.1}><h1 className="display">Power that keeps<br /><em>business moving.</em></h1></BlurIn><Reveal delay={.18}><p className="lead">Generator supply, rental, service and electrical systems built around the load, the site and the operation behind it.</p></Reveal><Reveal delay={.24}><div className="button-row"><Link className="button button-primary" to="/contact">Talk to the power team <span>↗</span></Link><Link className="button button-outline" to="/generators">Explore generators <span>↗</span></Link></div></Reveal></div><div className="home-hero-corner">NB / 01</div></section>
    <Marquee items={["Diesel generator systems", "Technical support", "Temporary power", "ATS / AMF panels", "Spare parts"]} />
    <section className="home-proof section"><div className="site-shell"><div className="section-heading"><Reveal><div><span className="eyebrow">Why NB</span><h2>A clearer way to<br /><span>keep power ready.</span></h2></div></Reveal><Reveal delay={.1}><p className="lead">The strongest generator businesses do more than sell equipment. They help customers make confident decisions, then stay accountable to the result.</p></Reveal></div><Stagger className="proof-grid">{proofPoints.map((point) => <motion.div key={point.no} variants={staggerItem}><SpotlightCard className="proof-card"><span>{point.no}</span><h3>{point.title}</h3><p>{point.text}</p><Link className="card-link" to={point.href}>{point.link} <span>↗</span></Link></SpotlightCard></motion.div>)}</Stagger></div></section>
    <section className="section"><div className="site-shell"><div className="section-heading"><Reveal><div><span className="eyebrow">A complete power partner</span><h2>Power systems<br /><span>without the guesswork.</span></h2></div></Reveal><Reveal delay={.1}><p className="lead">From selecting the right capacity to keeping the system ready, NB Engineering connects equipment, service and support in one practical workflow.</p></Reveal></div><Stagger className="card-grid card-grid-4">{services.slice(0, 8).map((service, index) => <motion.div key={service.slug || service.name} variants={staggerItem}><SpotlightCard className="service-card-modern"><span className="card-no">0{index + 1}</span><div><h3>{service.name}</h3><p>{service.description || "Application-led generator support for commercial, industrial and backup power requirements."}</p></div><Link className="card-link" to={`/services/${service.slug || "generator-sales"}`}>Explore service <span>↗</span></Link></SpotlightCard></motion.div>)}</Stagger></div></section>
    <section className="dark-section home-solution"><div className="site-shell detail-layout"><Reveal direction="left"><div className="home-solution-image"><img src={GENERATOR_IMAGE} alt={generators[0]?.name || "Industrial generator system"} /></div></Reveal><Reveal direction="right"><div><span className="eyebrow">02 / Generator solutions</span><h2 className="display">Built for the<br /><em>load ahead.</em></h2><p className="lead">Browse generator systems across standby, commercial and industrial applications, with equipment options from trusted global brands.</p><div className="stats-row"><div className="stat"><strong>60–500+</strong><span>KVA shown</span></div><div className="stat"><strong>24/7</strong><span>Support mindset</span></div></div><div className="button-row" style={{ marginTop: 26 }}><Link className="button button-primary" to="/generators">View generator range <span>↗</span></Link></div></div></Reveal></div></section>
    <JourneySection />
    <section className="section home-categories"><div className="site-shell"><div className="section-heading"><Reveal><div><span className="eyebrow">Solutions beyond the genset</span><h2>One system.<br /><span>Several moving parts.</span></h2></div></Reveal><Reveal delay={.12}><p className="lead">The dependable result comes from the details around the generator: control, changeover, service, parts and the people who understand the installation.</p></Reveal></div><div className="category-grid"><Reveal><SpotlightCard className="category-card category-card-large"><img src={PANEL_IMAGE} alt="ATS and AMF automation panel" /><div><span className="eyebrow">Automation</span><h3>ATS / AMF changeover</h3><Link className="card-link" to="/services/ats-panels">Explore automation <span>↗</span></Link></div></SpotlightCard></Reveal><Reveal delay={.1}><SpotlightCard className="category-card"><img src={CANOPY_GENERATOR_IMAGE} alt="Generator canopy system" /><div><span className="eyebrow">Installation</span><h3>Canopy & site work</h3><Link className="card-link" to="/services/canopy-work">Explore site work <span>↗</span></Link></div></SpotlightCard></Reveal><Reveal delay={.2}><SpotlightCard className="category-card"><img src={PARTS_STOCK_IMAGE} alt="Generator service parts" /><div><span className="eyebrow">Continuity</span><h3>Parts & maintenance</h3><Link className="card-link" to="/spare-parts">Explore support <span>↗</span></Link></div></SpotlightCard></Reveal></div></div></section>
    <section className="dark-section home-cta"><div className="site-shell"><Reveal><span className="eyebrow">Ready when you are</span><h2 className="display">Tell us what you<br /><em>need to power.</em></h2><p className="lead">Share the capacity, application or service requirement. We’ll help shape the next step.</p><Link className="button button-primary" to="/contact">Start an inquiry <span>↗</span></Link></Reveal></div></section>
  </main><Footer /></div>;
}
