import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Navbar from "../components/Navbar.jsx";
import Footer from "../components/Footer.jsx";
import { BlurIn, Marquee, Reveal, SpotlightCard, Stagger, staggerItem } from "../ui/MotionPrimitives.jsx";
import { HERO_IMAGE, PANEL_IMAGE, RENTAL_IMAGE } from "../ui/media.js";
import { getServices } from "../api/services.js";
import { getGenerators } from "../api/generators.js";
import { motion } from "motion/react";
import "../ui/site.css";

const fallbackServices = ["Generator sales", "Generator purchase", "Generator rental", "Generator repair", "Generator maintenance", "ATS panels"];
const fallbackGenerators = [{ name: "Diesel generator systems", kva: "20–1000+", image_url: HERO_IMAGE }];

export default function Home() {
  const [services, setServices] = useState(fallbackServices.map((name) => ({ name, slug: name.toLowerCase().replaceAll(" ", "-") })));
  const [generators, setGenerators] = useState(fallbackGenerators);
  useEffect(() => { Promise.allSettled([getServices(), getGenerators()]).then(([s,g]) => { if (s.status === "fulfilled" && s.value?.length) setServices(s.value); if (g.status === "fulfilled" && g.value?.length) setGenerators(g.value); }); }, []);
  return <div className="site-page"><Navbar /><main>
    <section className="home-hero dark-section"><div className="home-hero-media"><img src={HERO_IMAGE} alt="Industrial diesel generator" /></div><div className="home-hero-overlay" /><div className="site-shell home-hero-content"><Reveal><span className="eyebrow">Power generation / Islamabad</span></Reveal><BlurIn delay={.1}><h1 className="display">Power that keeps<br /><em>business moving.</em></h1></BlurIn><Reveal delay={.18}><p className="lead">Generator supply, rental, service and electrical systems built around the load, the site and the operation behind it.</p></Reveal><Reveal delay={.24}><div className="button-row"><Link className="button button-primary" to="/contact">Talk to the power team <span>↗</span></Link><Link className="button button-outline" to="/generators">Explore generators <span>↗</span></Link></div></Reveal></div><div className="home-hero-corner">NB / 01</div></section>
    <Marquee items={["Diesel generator systems", "Technical support", "Temporary power", "ATS / AMF panels", "Spare parts"]} />
    <section className="section"><div className="site-shell"><div className="section-heading"><Reveal><div><span className="eyebrow">A complete power partner</span><h2>Power systems<br /><span>without the guesswork.</span></h2></div></Reveal><Reveal delay={.1}><p className="lead">From selecting the right capacity to keeping the system ready, NB Engineering connects equipment, service and support in one practical workflow.</p></Reveal></div><Stagger className="card-grid card-grid-4">{services.slice(0,8).map((service,index) => <motion.div key={service.slug || service.name} variants={staggerItem}><SpotlightCard className="service-card-modern"><span className="card-no">0{index+1}</span><div><h3>{service.name}</h3><p>{service.description || "Application-led generator support for commercial, industrial and backup power requirements."}</p></div><Link className="card-link" to={`/services/${service.slug || "generator-sales"}`}>Explore service <span>↗</span></Link></SpotlightCard></motion.div>)}</Stagger></div></section>
    <section className="dark-section home-solution"><div className="site-shell detail-layout"><Reveal direction="left"><div className="home-solution-image"><img src={generators[0]?.image_url || HERO_IMAGE} alt={generators[0]?.name || "Generator system"} /></div></Reveal><Reveal direction="right"><div><span className="eyebrow">02 / Generator solutions</span><h2 className="display">Built for the<br /><em>load ahead.</em></h2><p className="lead">Browse diesel generator systems across standby, commercial and industrial applications, with equipment options from trusted global brands.</p><div className="stats-row"><div className="stat"><strong>20–1000+</strong><span>KVA range</span></div><div className="stat"><strong>24/7</strong><span>Support mindset</span></div></div><div className="button-row" style={{marginTop:26}}><Link className="button button-primary" to="/generators">View generator range <span>↗</span></Link></div></div></Reveal></div></section>
    <section className="section home-systems"><div className="site-shell"><div className="section-heading"><Reveal><div><span className="eyebrow">Beyond the genset</span><h2>Keep the whole<br /><span>system dependable.</span></h2></div></Reveal><Reveal delay={.12}><p className="lead">ATS panels, electrical control, rental power and maintenance are all part of the operating picture.</p></Reveal></div><div className="system-grid"><Reveal><SpotlightCard className="system-card large"><img src={PANEL_IMAGE} alt="Electrical control panel" /><div><span className="eyebrow">Control & distribution</span><h3>Power is more than the generator.</h3><Link className="card-link" to="/services/ats-panels">Explore ATS panels <span>↗</span></Link></div></SpotlightCard></Reveal><Reveal delay={.1}><SpotlightCard className="system-card"><img src={RENTAL_IMAGE} alt="Mobile generator" /><div><span className="eyebrow">Temporary power</span><h3>When the work cannot wait.</h3><Link className="card-link" to="/services/generator-rental">Explore rental power <span>↗</span></Link></div></SpotlightCard></Reveal></div></div></section>
    <section className="dark-section home-cta"><div className="site-shell"><Reveal><span className="eyebrow">Ready when you are</span><h2 className="display">Tell us what you<br /><em>need to power.</em></h2><p className="lead">Share the capacity, application or service requirement. We’ll help shape the next step.</p><Link className="button button-primary" to="/contact">Start an inquiry <span>↗</span></Link></Reveal></div></section>
  </main><Footer /></div>;
}
