"""add inquiries

Revision ID: 0d26675bc38f
Revises: 4931bb060e76
Create Date: 2026-09-26 23:39:46.848375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d26675bc38f'
down_revision: Union[str, Sequence[str], None] = '4931bb060e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('inquiry_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=250), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_id'), 'inquiries', ['id'], unique=False)
    op.create_index(op.f('ix_inquiries_inquiry_type'), 'inquiries', ['inquiry_type'], unique=False)
    op.create_index(op.f('ix_inquiries_phone'), 'inquiries', ['phone'], unique=False)
    op.create_index(op.f('ix_inquiries_status'), 'inquiries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inquiries_status'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_phone'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_inquiry_type'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_id'), table_name='inquiries')
    op.drop_table('inquiries')
    # ### end Alembic commands ###
