"""link inquiries and rentals to customers

Revision ID: 417654f05c13
Revises: a25d531964ec
Create Date: 2026-09-27 00:08:24.475340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417654f05c13'
down_revision: Union[str, Sequence[str], None] = 'a25d531964ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.add_column('inquiries', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_inquiries_phone'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_customer_id'), 'inquiries', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'inquiries', 'customers', ['customer_id'], ['id'])
    op.drop_column('inquiries', 'phone')
    op.drop_column('inquiries', 'company')
    op.drop_column('inquiries', 'email')
    op.drop_column('inquiries', 'name')
    op.add_column('rental_requests', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_rental_requests_phone'), table_name='rental_requests')
    op.create_index(op.f('ix_rental_requests_customer_id'), 'rental_requests', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'rental_requests', 'customers', ['customer_id'], ['id'])
    op.drop_column('rental_requests', 'phone')
    op.drop_column('rental_requests', 'company')
    op.drop_column('rental_requests', 'email')
    op.drop_column('rental_requests', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_requests', sa.Column('customer_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('rental_requests', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('rental_requests', sa.Column('company', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('rental_requests', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'rental_requests', type_='foreignkey')
    op.drop_index(op.f('ix_rental_requests_customer_id'), table_name='rental_requests')
    op.create_index(op.f('ix_rental_requests_phone'), 'rental_requests', ['phone'], unique=False)
    op.drop_column('rental_requests', 'customer_id')
    op.add_column('inquiries', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('inquiries', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('inquiries', sa.Column('company', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('inquiries', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.drop_index(op.f('ix_inquiries_customer_id'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_phone'), 'inquiries', ['phone'], unique=False)
    op.drop_column('inquiries', 'customer_id')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
