"""add contracts

Revision ID: 76b2c90d5f66
Revises: 788bce62bf1f
Create Date: 2026-09-30 21:52:19.990559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b2c90d5f66'
down_revision: Union[str, Sequence[str], None] = '788bce62bf1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_type'), 'contracts', ['contract_type'], unique=False)
    op.create_index(op.f('ix_contracts_customer_id'), 'contracts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contracts_end_date'), 'contracts', ['end_date'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_site_id'), 'contracts', ['site_id'], unique=False)
    op.create_index(op.f('ix_contracts_start_date'), 'contracts', ['start_date'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_title'), 'contracts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_title'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_start_date'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_site_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_end_date'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_customer_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_type'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
