"""add service history

Revision ID: 788bce62bf1f
Revises: d1041a649fdd
Create Date: 2026-09-30 21:34:39.671615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788bce62bf1f'
down_revision: Union[str, Sequence[str], None] = 'd1041a649fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=80), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.Column('work_performed', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_history_equipment_id'), 'service_history', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_service_history_id'), 'service_history', ['id'], unique=False)
    op.create_index(op.f('ix_service_history_service_date'), 'service_history', ['service_date'], unique=False)
    op.create_index(op.f('ix_service_history_service_type'), 'service_history', ['service_type'], unique=False)
    op.create_index(op.f('ix_service_history_status'), 'service_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_history_status'), table_name='service_history')
    op.drop_index(op.f('ix_service_history_service_type'), table_name='service_history')
    op.drop_index(op.f('ix_service_history_service_date'), table_name='service_history')
    op.drop_index(op.f('ix_service_history_id'), table_name='service_history')
    op.drop_index(op.f('ix_service_history_equipment_id'), table_name='service_history')
    op.drop_table('service_history')
    # ### end Alembic commands ###
