"""add rental requests

Revision ID: a25d531964ec
Revises: 0d26675bc38f
Create Date: 2026-09-26 23:47:52.938150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25d531964ec'
down_revision: Union[str, Sequence[str], None] = '0d26675bc38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generator_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('required_kva', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generator_id'], ['generators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_requests_generator_id'), 'rental_requests', ['generator_id'], unique=False)
    op.create_index(op.f('ix_rental_requests_id'), 'rental_requests', ['id'], unique=False)
    op.create_index(op.f('ix_rental_requests_phone'), 'rental_requests', ['phone'], unique=False)
    op.create_index(op.f('ix_rental_requests_status'), 'rental_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_requests_status'), table_name='rental_requests')
    op.drop_index(op.f('ix_rental_requests_phone'), table_name='rental_requests')
    op.drop_index(op.f('ix_rental_requests_id'), table_name='rental_requests')
    op.drop_index(op.f('ix_rental_requests_generator_id'), table_name='rental_requests')
    op.drop_table('rental_requests')
    # ### end Alembic commands ###
